[package]
name = "qq-server"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
async-stream.workspace = true
axum.workspace = true
directories.workspace = true
futures-util.workspace = true
getrandom.workspace = true
qq-core.workspace = true
qq-protocol.workspace = true
reqwest.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
